#161278871 Users should be able to create, read, update and delete articles
andela/ah-sealteam-frontend pull request #20
Opened 2018-12-19 15:30 UTC by botnetdobbs

#### What does this PR do?
```Creates functionality for users to view specific articles ```
#### Description of Task to be completed?
```A user should be able to view an article```
#### How should this be manually tested?
```
$ git fetch origin pull/19/head:feature/Users-should-be-able-to-read-an-article-162694516
$ git checkout feature/Users-should-be-able-to-read-an-article-162694516
$ source .env
$ npm install
$ npm start
```
#### What are the relevant pivotal tracker stories?

[#161278871](https://www.pivotaltracker.com/story/show/162694516)
 
#### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] At least 4 people have reviewed my PR
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] My PR has one commit.

- By @botnetdobbs and @gtsofa

2018-12-25 16:41 UTC, susanwere requested changes
Hi. Merry Christmas. Good job here. Would like to review but am encountering this error

<img width="1440" alt="screenshot 2018-12-25 at 19 39 31" src="https://user-images.githubusercontent.com/25789307/50424874-e7d56680-087c-11e9-9a28-09680e1da62e.png">

Would also like to know how to create, read, update and delete an article. the URLs that I should use. Maybe you could add more color to your PR?

2018-12-25 17:05 UTC, botnetdobbs commented
@Bluey95 Changes were made and the issue had been fixed. 
<img width="981" alt="screenshot 2018-12-25 at 20 04 13" src="https://user-images.githubusercontent.com/35170812/50425048-549e3000-0880-11e9-9455-80bdffbdc47b.png">

Just pull the recent changes and it should work as expected.

2018-12-25 17:08 UTC, Bluey95 commented
> @Bluey95 Changes were made and the issue had been fixed.
> <img alt="screenshot 2018-12-25 at 20 04 13" width="981" src="https://user-images.githubusercontent.com/35170812/50425048-549e3000-0880-11e9-9455-80bdffbdc47b.png">
> 
> Just pull the recent changes made to the branch and it should work as expected.

Okay. Thank you

2018-12-25 17:56 UTC, susanwere approved these changes

2018-12-27 07:32 UTC, rickynyairo approved these changes

2019-01-03 08:20 UTC, asheux approved these changes

2019-01-04 06:45 UTC, merged